### ISSUE TITLE
Enable plugin in *ts files

### ISSUE THREAD

**Issue by lukadelux** [pichillilorenzo/JavaScript-Completions#5]
Hi, plugin works great, however I need it to work in *.ts files. How can I enable that?

**Comment by pichillilorenzo** [comment]
to work with *.ts files i must add "source.ts" to the scope property for each completions json files, but i don't know if could be fine because there are other plugins that do something like that for this type of files, like this https://github.com/Microsoft/Typescript-Sublime-plugin.
However i think that this could be done with Python but i don't know this programming language!
